name: Endless Wordle Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare IP
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{secrets.VM_IP}} >> ~/.ssh/known_hosts

      - name: Copy files over
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: root
          key: ${{ secrets.VM_PRIVATE_KEY }}
          source: "./, !./ansible, !./.github"
          target: "/var/www/endless_wordle"