name: Configure VM

on:
  workflow_dispatch:

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python for Ansible
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: python -m pip install --upgrade pip && pip install ansible

      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.VM_IP}} >> ~/.ssh/known_hosts

      - name: Setup nginx conf contents
        run: echo "ENDLESS_WORDLE_NGINX_CONF=$(cat ./ansible/nginx/endless_wordle.conf | base64 -w 0)" >> $GITHUB_ENV

      - name: Create inventory from secret
        run: echo "${{ secrets.VM_IP }}" > inventory

      - name: Execute Ansible Playbook
        run: ansible-playbook -i inventory ./ansible/infra/setup.yaml --private-key ~/.ssh/id_rsa -u root
        env:
          ENDLESS_WORDLE_NGINX_CONF: ${{ env.ENDLESS_WORLDLE_NGINX_CONF }}
          CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
          ENDLESS_WORDLE_DOMAIN_NAME: ${{ secrets.ENDLESS_WORDLE_DOMAIN_NAME }}